api_login_check:
    path: /api/v1/auth/login

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_v1_controllers:
    resource: ../src/Controller/Api/V1/
    type: annotation
    prefix: '/api/v1/'